<nav class="navbar col-lg-7 navbar-expand-lg navbar-light">
<div class="container-fluid">
<div class="button d-grid mx-auto">
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
</div>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto mb-3 mb-lg-0">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="editinsurance">Založit nové pojištění</a></li>
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="insurences">Seznam pojištění</a></li>
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="editclient">Založit nového klienta</a></li>
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="clients">Seznam zákazníků</a></li>
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="clients">Odhlásit</a></li>
    </ul>
    </div>
</div>
</nav>
