<html lang="en">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="style.css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="style.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keyword ?>" />
        <title><?= $title ?></title>
    </head>
<body>
  <article>
        <div class="container">
            <header class="border-bottom">
                <div class="row col-md-auto text-center">
                    <div class="col-lg-5"><div><h1>PNB Pojišťovna</h1><p class="text-muted">Zachovejte si zdravý rozum</p></div>
                </div>
                <nav class="navbar col-lg-7 navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <div class="button d-grid mx-auto">
                   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                </div>
                    <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-3 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="uvod">Úvod</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="insurance">Pojištění</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="register">Staň se naším klientem</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="signup">Moje pojištění</a></li>
                        </xli>
                    </ul>
                    </div>
                </div>
                </nav>

                </div>
            </header>
        </div>
        <?php foreach ($message as $mes) : ?>
          <p class="text-center my-2"><?= $mes ?></p>
        <?php endforeach ?>

      <section class="container">
            <?php $this->controler->showwiew(); ?>
        </section>

        <footer>
            <div class="d.flex-row-reverse text-center">
            <p></p>
            </div>
        </footer>
</article>
</body>
</html>

</body>
</html>
