<div class="row">
                <div class="col-md-6"><div id="#zaciname"></div><div class="maintext"><h2>Začínáme</h2>
                  Naše firma má 15 let zkušeností s vedením účetnictví, daňové evidence a zpracování mezd.
                  Také je lektorkou v kurzech Účetnictví, Daňová evidence,Našimi klienty jsou převážně živnostníci,
                  menší společnosti a.s. a s.r.o., společenství vlastníků a zájmové organizace. Spolupracujeme s
                  menším množstvím zákazníků a máme tak čas se jim plně věnovat. Své klienty známe osobně, známe
                  Naše firma má 15 let zkušeností s vedením účetni</p></div></div>
                <div class="col-md-6"><div class="mainlogo"><img src="Photo/mainlogo.png" class="img-fluid"></div></div>
                <div class="col-md-6"><div class="mainlogo"><iframe class="container"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2841.4363511794536!2d38.93561148575533!3d15.320588212194139!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x166df26789b79413%3A0x50bdc6f201e2951e!2sMelotti%20Lager%20Beer!5e0!3m2!1scs!2scz!4v1632094771844!5m2!1scs!2scz"
                    height="400px" loading="lazy"></iframe></div></div>
                <div class="col-md-6"><div id="kdojsme"></div><div class="maintext"><h2>Kdo jsme?</h2><p>The following div element's opacity is 0.5.
                    Note that both the text and the background-color are affected by the opacity level
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper diam at erat
                    pulvinar, at pulvinar felis blandit..
                    The following div element's opacity is 0.5.
                    Note that both the text and the background-color are affected by the opacity level
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper diam at erat
                    pulvinar, at pulvinar felis blandit..</p></div></div>
                <div class="col-md-6"><div id="codelame"></div><div class="maintext"><h2>Co děláme?</h2><p>The following div element's opacity is 0.5.
                    Note that both the text and the background-color are affected by the opacity level
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper diam at erat
                    pulvinar, at pulvinar felis blandit..
                    The following div element's opacity is 0.5.
                    Note that both the text and the background-color are affected by the opacity level
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper diam at erat
                    pulvinar, at pulvinar felis blandit..</p></div></div>
                <div class="col-md-6"><div class="mainlogo"><img src="Photo/codelame.jpg" class="img-fluid"></div></div>
                <div class="col-md-6"><div class="mainlogo"><img src="Photo/jakemamevysledky.jpg" class="img-fluid"></div></div>
                <div class="col-md-6"><div id="jakemamevysledky"></div><div class="maintext"><h2>Jaké máme výsledky:</h2><p>The following div element's opacity is 0.5.
                    Note that both the text and the background-color are affected by the opacity level
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper diam at erat
                    pulvinar, at pulvinar felis blandit..
                    The following div element's opacity is 0.5.
                    Note that both the text and the background-color are affected by the opacity level
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper diam at erat
                    pulvinar, at pulvinar felis blandit..</p></div></div>
            </div>
